[package]
name = "uprof-exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus = "0.13"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }