services:
  uprof-exporter:
    image: justagod/amd-uprof-exporter
    restart: unless-stopped
    container_name: uprof-exporter
    privileged: true
    environment:
      - HOST_HOSTNAME=${HOSTNAME}
    ports:
      - "7804:9100"
    volumes:
      - "/dev/cpu:/dev/cpu:ro"
      - "./data:/var/uprof"