services:
  uprof-exporter:
    image: justagod/amd-uprof-exporter
    container_name: uprof-exporter
    privileged: true
    stdin_open: true
    ports:
      - "7804:9100"
    volumes:
      - "/dev/cpu:/dev/cpu:ro"
      - "./data:/var/uprof"